// Tests assert byte-for-byte equality with what PackRelayCloud's
// src/lib/canonical-json.ts produces. Every expected string in here
// was either:
//   (a) generated by running canonicalize(input) in the cloud's test
//       harness, or
//   (b) derived from JSON.stringify semantics that canonicalize()
//       defers to (same rules as JSON.stringify for strings/numbers).
//
// If a test here fails it almost certainly means the C# port has
// diverged from the cloud and signatures generated by KC would fail
// verification on the cloud — fix the C# side, not the test.

using System;
using System.Text;
using KitsuneCommand.Services.PackRelay;
using Newtonsoft.Json.Linq;
using NUnit.Framework;

namespace KitsuneCommand.Tests.Services.PackRelay
{
    [TestFixture]
    public class CanonicalJsonTests
    {
        // ---- Primitives ----

        [Test]
        public void Encodes_Null()
        {
            Assert.That(CanonicalJson.EncodeToString(JValue.CreateNull()), Is.EqualTo("null"));
        }

        [Test]
        public void Encodes_True()
        {
            Assert.That(CanonicalJson.EncodeToString(new JValue(true)), Is.EqualTo("true"));
        }

        [Test]
        public void Encodes_False()
        {
            Assert.That(CanonicalJson.EncodeToString(new JValue(false)), Is.EqualTo("false"));
        }

        [Test]
        public void Encodes_Integer_NoDecimal()
        {
            // JSON.stringify(45105) === "45105"
            Assert.That(CanonicalJson.EncodeToString(new JValue(45105L)), Is.EqualTo("45105"));
        }

        [Test]
        public void Encodes_NegativeInteger()
        {
            Assert.That(CanonicalJson.EncodeToString(new JValue(-7L)), Is.EqualTo("-7"));
        }

        [Test]
        public void Encodes_IntegerValuedDouble_AsInteger()
        {
            // JSON.stringify(45105.0) === "45105" — no trailing .0.
            // Newtonsoft promotes 45105.0 to JTokenType.Float, but we
            // still need to emit "45105" so signatures match.
            Assert.That(CanonicalJson.EncodeToString(new JValue(45105.0)), Is.EqualTo("45105"));
        }

        [Test]
        public void Encodes_NonIntegerDouble_RoundTrip()
        {
            // JSON.stringify(3.14) === "3.14"
            Assert.That(CanonicalJson.EncodeToString(new JValue(3.14)), Is.EqualTo("3.14"));
        }

        [Test]
        public void Encodes_NonFiniteDouble_Throws()
        {
            Assert.Throws<InvalidOperationException>(
                () => CanonicalJson.EncodeToString(new JValue(double.NaN)));
            Assert.Throws<InvalidOperationException>(
                () => CanonicalJson.EncodeToString(new JValue(double.PositiveInfinity)));
        }

        // ---- Strings ----

        [Test]
        public void Encodes_EmptyString()
        {
            Assert.That(CanonicalJson.EncodeToString(new JValue("")), Is.EqualTo("\"\""));
        }

        [Test]
        public void Encodes_PlainString()
        {
            Assert.That(CanonicalJson.EncodeToString(new JValue("hello")), Is.EqualTo("\"hello\""));
        }

        [Test]
        public void Encodes_String_EscapesQuote()
        {
            Assert.That(
                CanonicalJson.EncodeToString(new JValue("a\"b")),
                Is.EqualTo("\"a\\\"b\""));
        }

        [Test]
        public void Encodes_String_EscapesBackslash()
        {
            Assert.That(
                CanonicalJson.EncodeToString(new JValue("a\\b")),
                Is.EqualTo("\"a\\\\b\""));
        }

        [Test]
        public void Encodes_String_DoesNotEscapeForwardSlash()
        {
            // Matches JS JSON.stringify("a/b") === "\"a/b\"" — RFC
            // allows escaping it, JSON.stringify doesn't, and we
            // mirror JSON.stringify so verify works.
            Assert.That(
                CanonicalJson.EncodeToString(new JValue("a/b")),
                Is.EqualTo("\"a/b\""));
        }

        [Test]
        public void Encodes_String_EscapesNewlineTabReturn()
        {
            Assert.That(
                CanonicalJson.EncodeToString(new JValue("a\nb\tc\rd")),
                Is.EqualTo("\"a\\nb\\tc\\rd\""));
        }

        [Test]
        public void Encodes_String_EscapesControlChar_AsUnicode()
        {
            // 0x01 — start-of-heading. JSON.stringify emits .
            Assert.That(
                CanonicalJson.EncodeToString(new JValue("")),
                Is.EqualTo("\"\\u0001\""));
        }

        [Test]
        public void Encodes_String_NonAscii_LiteralUtf8()
        {
            // JSON.stringify("café") === "\"café\"" (literal é).
            // The é → UTF-8 bytes is the GetBytes step's job.
            const string s = "café"; // café
            Assert.That(CanonicalJson.EncodeToString(new JValue(s)), Is.EqualTo("\"café\""));

            // And the bytes must round-trip as UTF-8.
            var bytes = CanonicalJson.Encode(new JValue(s));
            var asUtf8 = Encoding.UTF8.GetString(bytes);
            Assert.That(asUtf8, Is.EqualTo("\"café\""));
        }

        // ---- Arrays ----

        [Test]
        public void Encodes_EmptyArray()
        {
            Assert.That(CanonicalJson.EncodeToString(new JArray()), Is.EqualTo("[]"));
        }

        [Test]
        public void Encodes_IntegerArray()
        {
            Assert.That(
                CanonicalJson.EncodeToString(new JArray(1, 2, 3)),
                Is.EqualTo("[1,2,3]"));
        }

        [Test]
        public void Encodes_MixedArray_NoWhitespace()
        {
            // No spaces anywhere. The TS canonicalize() joins with bare
            // commas; the C# port must too.
            Assert.That(
                CanonicalJson.EncodeToString(new JArray(1, "hi", true, JValue.CreateNull())),
                Is.EqualTo("[1,\"hi\",true,null]"));
        }

        // ---- Objects ----

        [Test]
        public void Encodes_EmptyObject()
        {
            Assert.That(CanonicalJson.EncodeToString(new JObject()), Is.EqualTo("{}"));
        }

        [Test]
        public void Encodes_Object_SortsKeysLexicographically()
        {
            // Insertion order is b, a. Output must reorder to a, b
            // because Object.keys(obj).sort() is the TS spec.
            var obj = new JObject
            {
                ["b"] = 2,
                ["a"] = 1,
            };
            Assert.That(
                CanonicalJson.EncodeToString(obj),
                Is.EqualTo("{\"a\":1,\"b\":2}"));
        }

        [Test]
        public void Encodes_Object_OrdinalSort_NotCultureSort()
        {
            // Uppercase 'Z' (0x5A) sorts before lowercase 'a' (0x61)
            // in ordinal/codepoint order — but AFTER 'a' in many
            // culture-aware sorts (e.g. en-US). The TS sort is
            // codepoint-only; ours must match.
            var obj = new JObject
            {
                ["a"] = 1,
                ["Z"] = 2,
            };
            Assert.That(
                CanonicalJson.EncodeToString(obj),
                Is.EqualTo("{\"Z\":2,\"a\":1}"));
        }

        [Test]
        public void Encodes_NestedObject_SortsAtEveryLevel()
        {
            var inner = new JObject { ["y"] = 2, ["x"] = 1 };
            var outer = new JObject
            {
                ["b"] = inner,
                ["a"] = 0,
            };
            Assert.That(
                CanonicalJson.EncodeToString(outer),
                Is.EqualTo("{\"a\":0,\"b\":{\"x\":1,\"y\":2}}"));
        }

        // ---- Realistic manifest shape ----

        [Test]
        public void Encodes_ManifestExample()
        {
            // Approximates a tiny PackRelay manifest — display name,
            // version, three files. Keys deliberately inserted out of
            // order to prove the canonicalizer reorders them.
            var manifest = new JObject
            {
                ["version"] = "1.2.3",
                ["displayName"] = "Test Pack",
                ["slug"] = "test-pack",
                ["files"] = new JArray
                {
                    new JObject
                    {
                        ["size"] = 1024L,
                        ["sha256"] = "abc123",
                        ["path"] = "Mods/Test/ModInfo.xml",
                    },
                    new JObject
                    {
                        ["sha256"] = "def456",
                        ["path"] = "Mods/Test/Config/items.xml",
                        ["size"] = 2048L,
                    },
                },
            };

            // Expected: top-level keys sorted (displayName, files,
            // slug, version), file objects' keys sorted (path,
            // sha256, size), no whitespace.
            const string expected =
                "{\"displayName\":\"Test Pack\","
                + "\"files\":["
                + "{\"path\":\"Mods/Test/ModInfo.xml\",\"sha256\":\"abc123\",\"size\":1024},"
                + "{\"path\":\"Mods/Test/Config/items.xml\",\"sha256\":\"def456\",\"size\":2048}"
                + "],"
                + "\"slug\":\"test-pack\","
                + "\"version\":\"1.2.3\"}";

            Assert.That(CanonicalJson.EncodeToString(manifest), Is.EqualTo(expected));
        }

        [Test]
        public void Encode_ReturnsUtf8Bytes()
        {
            var bytes = CanonicalJson.Encode(new JValue("hi"));
            Assert.That(bytes, Is.EqualTo(Encoding.UTF8.GetBytes("\"hi\"")));
        }
    }
}
