global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using Newtonsoft.Json;
global using KitsuneCommand.Abstractions;
global using KitsuneCommand.Abstractions.Models;
